name: Release By PR Comment

on:
  issue_comment:

# Example output: in a PR branch (head) named `feature-1 to a target branch (base) of `release-v1`, you'll see:
  # github.base_ref: release-v1
  # github.head_ref: feature-1
  # github.ref: refs/pull/2/merge

jobs:
  if_release_comment:
    if: "${{ github.event.issue.pull_request && startsWith(github.event.issue.title, 'chore(release): v') && startsWith(github.event.comment.body, '/release') }}"
    runs-on: ubuntu-latest
    steps:
      - name: "Check if user has write access"
        uses: "lannonbr/repo-permission-check-action@2.0.0"
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Checkout
        uses: actions/checkout@v2
        if: success()
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - run: |
          echo "HEAD_SHA=${{steps.comment-branch.outputs.head_sha}}" >> $GITHUB_ENV

      - name: Setup Version & Environment Variables
        run: |
          DIST_VERSION=$(node -e "console.log(require('./package.json').version)")
          echo "DIST_VERSION=${DIST_VERSION}" >> $GITHUB_ENV
          echo "DIST_TAG=fakeLatest" >> $GITHUB_ENV
          echo $PR_CONTENT >> ./releaselog.md
        env:
          PR_CONTENT: ${{ github.event.issue.body }}


      - uses: actions/github-script@v6
        id: run-check-suite
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./scripts/github/notifyReleaseResult.js')
            return await script('Release', {github, context, core}, 'start')

      - name: Setup CHECK_RUN_ID Environment Variables
        run: |
          echo "CHECK_RUN_ID=${{steps.run-check-suite.outputs.result}}" >> $GITHUB_ENV

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      # 安装依赖并构建
      - name: Install dependencies & Build
        run: |
          npm i

      - name: Publish version
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
          node ./scripts/publishInCI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.DIST_VERSION }}
          release_name: v${{ env.DIST_VERSION }}
          body_path: ./releaselog.md
          draft: true
          prerelease: true

      # 发布失败后，更新 checkRun 状态
      - uses: actions/github-script@v6
        if: failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./scripts/github/notifyReleaseResult.js')
            return await script('Release', {github, context, core}, 'failure')

      - uses: actions/github-script@v6
        if: success()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const script = require('./scripts/github/notifyReleaseResult.js')
            return await script('Release', {github, context, core}, 'end')
